### PR TITLE
Filter out fields with #[codec(skip)]

### LINKED ISSUE #14: Exclude fields with #[codec(skip)] attribute
# 1. Problem

Using subxt, invoke [Call](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create) to create a new NFT collection provided by [pallet_nfts](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0/frame/nfts). The JSON-RPC call is not made and this error message is returned:

```
Error at settings.config: Cannot encode Tuple into type with ID 11
```

# 2. Steps to Reproduce

Reproducing the problem requires:

1. Bespoke substrate node with the [pallet_nfts](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts) enabled, running locally, and started with the _--dev_ flag.
2. CLI application (client) to invoke [Call](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create) to create a new NFT collection.

## 2.1. Substrate Node

The [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node) has been extended to include the [pallet_nfts](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts).

1. Obtain the source code for the bespoke substrate node.

   ```bash
   git clone -b with-extras https://github.com/gh-mc/substrate-contracts-node.git
   ```

2. Compile the code.

   ```bash
   cd substrate-contracts-node
   cargo build --release
   ```
   
   NOTE: cargo has been installed from the stable channel using rustup.
   
   ```bash
   > rustup show
   
   Default host: x86_64-unknown-linux-gnu
   rustup home:  /home/ubuntu/.rustup
   
   installed targets for active toolchain
   --------------------------------------
   
   wasm32-unknown-unknown
   x86_64-unknown-linux-gnu
   
   active toolchain
   ----------------
   
   stable-x86_64-unknown-linux-gnu (default)
   rustc 1.71.0 (8ede3aae2 2023-07-12)
   ```

3. Start the substrate node.

   ```bash
   ./target/release/substrate-contracts-node --dev
   ```

## 2.2. Client

A simple CLI application has been created to invoke [Call](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create) to create a new NFT collection provided by [pallet_nfts](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0/frame/nfts).

1. Obtain the source code for the client application.

   ```bash
   git clone https://github.com/gh-mc/patch-scale-client.git
   ```

2. Compile the code.

   ```bash
   cargo build
   ```

3. Execute the binary to trigger the exception.

   ```bash
   target/debug/client-fails
   ```

# 3. Analysis

This section reviews the "server" and "client" components individually to identify the root cause of the problem.
The code for [pallet_nfts](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0/frame/nfts), [subxt](https://github.com/paritytech/subxt/tree/v0.30.0), [parity-scale-codec](https://github.com/paritytech/parity-scale-codec/blob/parity-scale-codec-v3.6.4), and [scale-encode](https://docs.rs/scale-encode/0.4.0/scale_encode/) has been examined.

## 3.1. Substrate Node

Recall the error message begins with `Error at settings.config`.

The [Call](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create) to create a new NFT collection is invoked with an argument named [config](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create.field.config).
The config argument is of type [CollectionConfig](https://docs.rs/pallet-nfts/latest/pallet_nfts/struct.CollectionConfig.html), which contains a field named [settings](https://docs.rs/pallet-nfts/latest/pallet_nfts/struct.CollectionConfig.html#structfield.settings).
The settings field is of type [CollectionSettings](https://docs.rs/pallet-nfts/latest/pallet_nfts/struct.CollectionSettings.html), which is a wrapper type for [BitFlags](https://docs.rs/enumflags2/0.7.7/enumflags2/struct.BitFlags.html).

The [pallet_nfts](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0/frame/nfts) depends on [enumflags2](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts/Cargo.toml#L17), which provides the [BitFlags](https://docs.rs/enumflags2/0.7.7/enumflags2/struct.BitFlags.html) struct.
Additionally, the [pallet_nfts](https://github.com/paritytech/substrate/tree/polkadot-v1.0.0/frame/nfts) implements a rust macro named [impl_codec_bitflags](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts/src/macros.rs) to encode / decode the [BitFlags](https://docs.rs/enumflags2/0.7.7/enumflags2/struct.BitFlags.html) struct.

[Here](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts/src/types.rs#L239-L258) is the code to define the CollectionSetting enum, and represent it as a u64 primitive type.
[Here](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts/src/types.rs#L275) is the statement to [impl_codec_bitflags](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts/src/macros.rs) macro, which will generate the rust code to encode / decode a field of type BitFlags&lt;CollectionSetting&gt; to / from a u64 primitive type.

## 3.2. Client

The [subxt](https://github.com/paritytech/subxt/tree/v0.30.0) crate generates rust code to invoke JSON-RPC calls provided by [pallet_nfts](https://github.com/paritytech/substrate/blob/polkadot-v1.0.0/frame/nfts) on a bespoke substrate node.

The [Call](https://docs.rs/pallet-nfts/latest/pallet_nfts/pallet/enum.Call.html#variant.create) to create a new NFT collection, is invoked with a _call\_data_ type generated by subxt.
Within the _call\_data_ type the _config_ and _settings_ fields are defined. The settings field is of type BitFlags<CollectionSetting>.

The subxt generated code for the BitFlags tuple struct is:

```rust
#[derive(
    :: subxt :: ext :: codec :: CompactAs,
    :: subxt :: ext :: codec :: Decode,
    :: subxt :: ext :: codec :: Encode,
    :: subxt :: ext :: scale_decode :: DecodeAsType,
    :: subxt :: ext :: scale_encode :: EncodeAsType,
    Debug,
)]
# [codec (crate = :: subxt :: ext :: codec)]
#[decode_as_type(crate_path = ":: subxt :: ext :: scale_decode")]
#[encode_as_type(crate_path = ":: subxt :: ext :: scale_encode")]
pub struct BitFlags<_0>(
    pub ::core::primitive::u64,
    #[codec(skip)] pub ::core::marker::PhantomData<_0>,
);
```

The field marked with the attribute `#[codec(skip)]` is included in the code generated for the EncodeAsType trait for BitFlags. This is represented below by the field containing the statement `_1 as &dyn ::subxt::ext::scale_encode::EncodeAsType`.

```rust
impl<_0> ::subxt::ext::scale_encode::EncodeAsType for BitFlags<_0>
where
    _0: ::subxt::ext::scale_encode::EncodeAsType,
{
    fn encode_as_type_to(
        &self,
        __encode_as_type_type_id: u32,
        __encode_as_type_types: &::subxt::ext::scale_encode::PortableRegistry,
        __encode_as_type_out: &mut Vec<u8>,
    ) -> Result<(), ::subxt::ext::scale_encode::Error> {
        let BitFlags(_0, _1) = self;
        ::subxt::ext::scale_encode::Composite(
                [
                    (
                        None as Option<&'static str>,
                        _0 as &dyn ::subxt::ext::scale_encode::EncodeAsType,
                    ),
                    (
                        None as Option<&'static str>,
                        _1 as &dyn ::subxt::ext::scale_encode::EncodeAsType,
                    ),
                ]
                    .into_iter(),
            )
            .encode_as_type_to(
                __encode_as_type_type_id,
                __encode_as_type_types,
                __encode_as_type_out,
            )
    }
}
```

The Composite&lt;Vals&gt; is to be encoded as a primitive type. However, the [vals_iter](https://github.com/paritytech/scale-encode/blob/v0.4.0/scale-encode/src/impls/composite.rs#L59) variable contains more than one field. It cannot be converted to a primitive type, [this](https://github.com/paritytech/scale-encode/blob/v0.4.0/scale-encode/src/impls/composite.rs#L120-L126) code is reached, and the error is returned. Resulting in the second half of the error message `Cannot encode Tuple into type with ID 11`.

# 4. Proposed Solution

The proposed change is to be made in the [scale-encode](https://docs.rs/scale-encode/0.4.0/scale_encode/) crate.
Specifically, the [EncodeAsType](https://docs.rs/scale-encode/latest/scale_encode/trait.EncodeAsType.html) trait, generated by the procedural macro [EncodeAsType](https://github.com/paritytech/scale-encode/blob/v0.4.0/scale-encode-derive/src/lib.rs#L202-L203), should exclude fields marked with the `#[codec(skip)]` attribute from the generated [Composite](https://docs.rs/scale-encode/0.4.0/scale_encode/struct.Composite.html) struct.

Logic equivalent to the function [should_skip](https://github.com/paritytech/parity-scale-codec/blob/parity-scale-codec-v3.6.4/derive/src/utils.rs#L102-L113) within the [parity-scale-codec-derive](https://docs.rs/parity-scale-codec-derive/3.6.4/parity_scale_codec_derive/) crate should be implemented within the [scale-encode](https://docs.rs/scale-encode/0.4.0/scale_encode/) crate. I do not believe the [should_skip](https://github.com/paritytech/parity-scale-codec/blob/parity-scale-codec-v3.6.4/derive/src/utils.rs#L102-L113) function can be exported from [parity-scale-codec-derive](https://docs.rs/parity-scale-codec-derive/3.6.4/parity_scale_codec_derive/) because:

```
error: `proc-macro` crate types currently cannot export any items other than functions tagged with `#[proc_macro]`, `#[proc_macro_derive]`, or `#[proc_macro_attribute]`
```

I'm not aware of a way the [should_skip](https://github.com/paritytech/parity-scale-codec/blob/parity-scale-codec-v3.6.4/derive/src/utils.rs#L102-L113) function can be modified to comply with these restrictions.

# 5. Verification

This section verifies the proposed solution resolves the problem, and the call to the rpc endpoint is made.

## 5.1. Substrate Node

Refer to section 2.1 to build, and run the bespoke substrate node (steps 1 to 3).

## 5.2. Client

Refer to section 2.2 to build the CLI application (steps 1 and 2).

3. Execute the binary to successfully create the NFT collection.

   ```bash
   target/debug/client-patched
   ```

### PR DESCRIPTION
**Pull request by jsdw**
Builds on #15 to tidy and add a couple of tests to confirm.

Supports `#[coded(skip)]` or `#[encode_as_type(skip)]` attrs to skip over fields we don't care about encoding.

This allows fields that don't impl `EncodeAsType` to exist (as long as they are skipped) and allows logic around single-field composites to kick in to encode to numbers or whatever.

~~A companion PR in `scale-decode` will be opened too to mirror this.~~ Actually, it's already present there!

Closes #14

### CODE REVIEW

**Review by lexnv — APPROVED** [review]
LGTM!

File: scale-encode-derive/src/lib.rs [hunk 1]
```diff
@@ -124,6 +128,7 @@ fn generate_struct_impl(
             }
         }
         impl #impl_generics #path_to_scale_encode::EncodeAsFields for #path_to_type #ty_generics #where_clause {
+            #[allow(unused_variables)]
```
Comment (niklasad1) [inline scale-encode-derive/src/lib.rs:131]: why is this needed now? doesn't matter to me

File: scale-encode-derive/src/lib.rs [hunk 2]
```diff
@@ -255,3 +265,16 @@ impl TopLevelAttrs {
         Ok(res)
     }
 }
+
+// Since we only care about `skip` at the moment, we just expose this helper,
```
Comment (niklasad1) [inline scale-encode-derive/src/lib.rs]: I had some troubles to understand 

```suggestion
// Checks if the attributes contain `skip`.
//
// NOTE: Since we only care about `skip` at the moment, we just expose this helper,
// but if we add more attrs we can expose `FieldAttrs` properly:
```

**Review by niklasad1 — APPROVED** [review]

File: scale-encode-derive/src/lib.rs (hunk 1 above)
Comment (jsdw) [reply scale-encode-derive/src/lib.rs:131]: It seemed to matter if there was a strict that one or fields were being skipped on, because the restructuring matches on all the field names (I could make it not do that, but then it needs to use `..` in some cases but not others to ignore non matched things, so I didn't bother.

probably things could be tweaked a bit to avoid this!

File: scale-encode-derive/src/lib.rs [hunk 3]
```diff
@@ -255,3 +265,19 @@ impl TopLevelAttrs {
         Ok(res)
     }
 }
+
+// Checks if the attributes contain `skip`.
+//
+// NOTE: Since we only care about `skip` at the moment, we just expose this helper,
+// but if we add more attrs we can expose `FieldAttrs` properly:
+// but if we add more attrs we can expose `FieldAttrs` properly:
```
Comment (niklasad1) [inline scale-encode-derive/src/lib.rs]:
```suggestion
```
